[{"coordinates":"pkg:conda/pycrypto@2.6.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pycrypto@2.6.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pycurl@7.43.0.3","reference":"https://ossindex.sonatype.org/component/pkg:conda/pycurl@7.43.0.3","vulnerabilities":[]},{"coordinates":"pkg:conda/pyflakes@2.1.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyflakes@2.1.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pygments@2.4.2","reference":"https://ossindex.sonatype.org/component/pkg:conda/pygments@2.4.2","vulnerabilities":[]},{"coordinates":"pkg:conda/pylint@2.3.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pylint@2.3.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pyodbc@4.0.26","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyodbc@4.0.26","vulnerabilities":[]},{"coordinates":"pkg:conda/pyopenssl@19.0.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyopenssl@19.0.0","vulnerabilities":[]},{"coordinates":"pkg:conda/pyparsing@2.4.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyparsing@2.4.0","vulnerabilities":[]},{"coordinates":"pkg:conda/pyqt@5.9.2","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyqt@5.9.2","vulnerabilities":[]},{"coordinates":"pkg:conda/pyrsistent@0.14.11","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyrsistent@0.14.11","vulnerabilities":[]},{"coordinates":"pkg:conda/pysocks@1.7.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pysocks@1.7.0","vulnerabilities":[]},{"coordinates":"pkg:conda/pytables@3.5.2","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytables@3.5.2","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest@5.0.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest@5.0.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest-arraydiff@0.3","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest-arraydiff@0.3","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest-astropy@0.5.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest-astropy@0.5.0","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest-doctestplus@0.3.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest-doctestplus@0.3.0","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest-openfiles@0.3.2","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest-openfiles@0.3.2","vulnerabilities":[]},{"coordinates":"pkg:conda/pytest-remotedata@0.3.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytest-remotedata@0.3.1","vulnerabilities":[]},{"coordinates":"pkg:conda/python@3.7.3","reference":"https://ossindex.sonatype.org/component/pkg:conda/python@3.7.3","vulnerabilities":[{"id":"156d71e4-6ed5-4d5f-ae47-7d57be01d387","title":"[CVE-2019-16056] An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x throu...","description":"An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.","cvssScore":0.0,"cve":"CVE-2019-16056","reference":"https://ossindex.sonatype.org/vuln/156d71e4-6ed5-4d5f-ae47-7d57be01d387"},{"id":"1b3756ee-19f2-4e67-ba56-9abe066f312a","title":"[CVE-2019-16935] The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, an...","description":"The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.","cvssScore":0.0,"cve":"CVE-2019-16935","reference":"https://ossindex.sonatype.org/vuln/1b3756ee-19f2-4e67-ba56-9abe066f312a"},{"id":"bed20c8a-5e03-43f4-ad55-55d2ff0659cf","title":"[CVE-2019-18348] An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Py...","description":"An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.)","cvssScore":0.0,"cve":"CVE-2019-18348","reference":"https://ossindex.sonatype.org/vuln/bed20c8a-5e03-43f4-ad55-55d2ff0659cf"}]},{"coordinates":"pkg:conda/python-dateutil@2.8.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/python-dateutil@2.8.0","vulnerabilities":[]},{"coordinates":"pkg:conda/python-libarchive-c@2.8","reference":"https://ossindex.sonatype.org/component/pkg:conda/python-libarchive-c@2.8","vulnerabilities":[]},{"coordinates":"pkg:conda/python.app@2","reference":"https://ossindex.sonatype.org/component/pkg:conda/python.app@2","vulnerabilities":[]},{"coordinates":"pkg:conda/pytz@2019.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pytz@2019.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pywavelets@1.0.3","reference":"https://ossindex.sonatype.org/component/pkg:conda/pywavelets@1.0.3","vulnerabilities":[]},{"coordinates":"pkg:conda/pyyaml@5.1.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyyaml@5.1.1","vulnerabilities":[]},{"coordinates":"pkg:conda/pyzmq@18.0.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/pyzmq@18.0.0","vulnerabilities":[]},{"coordinates":"pkg:conda/qt@5.9.7","reference":"https://ossindex.sonatype.org/component/pkg:conda/qt@5.9.7","vulnerabilities":[]},{"coordinates":"pkg:conda/qtawesome@0.5.7","reference":"https://ossindex.sonatype.org/component/pkg:conda/qtawesome@0.5.7","vulnerabilities":[]},{"coordinates":"pkg:conda/qtconsole@4.5.1","reference":"https://ossindex.sonatype.org/component/pkg:conda/qtconsole@4.5.1","vulnerabilities":[]},{"coordinates":"pkg:conda/qtpy@1.8.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/qtpy@1.8.0","vulnerabilities":[]},{"coordinates":"pkg:conda/readline@7.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/readline@7.0","vulnerabilities":[]},{"coordinates":"pkg:conda/requests@2.22.0","reference":"https://ossindex.sonatype.org/component/pkg:conda/requests@2.22.0","vulnerabilities":[]}]
